volumes:
  pgdata:
  static_files:

services:
  pg:
    image: postgres:16-alpine
    container_name: meteogarden_pg
    restart: unless-stopped
    env_file:
      - .postgres.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: meteogarden_redis
    restart: unless-stopped

  api:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: meteogarden_api
    restart: unless-stopped
    env_file:
      - .django.env
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8000"
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro

  worker:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: meteogarden_worker
    restart: unless-stopped
    command: celery -A config worker -l info
    env_file:
      - .django.env
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro

  beat:
    image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
    container_name: meteogarden_beat
    restart: unless-stopped
    command: celery -A config beat -l info
    env_file:
      - .django.env
    depends_on:
      pg:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./firebase-key.json:/app/firebase-key.json:ro