sonar.projectKey=pes2526q2-13-gei-upc_MeteoGarden-Backend
sonar.organization=pes2526q2-13-gei-upc

sonar.sources=.
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/.venv/**,**/venv/**
sonar.coverage.exclusions=**/migrations/**,**/tests/**
sonar.cpd.exclusions=**/migrations/**