# Generated by Django 5.2.12 on 2026-03-17 11:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("city", models.CharField(max_length=50)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("catalan", "Catalan"),
                            ("spanish", "Spanish"),
                            ("english", "English"),
                        ],
                        default="catalan",
                        max_length=50,
                    ),
                ),
                ("lastEntry", models.DateTimeField(auto_now=True)),
                ("numPlantsCollected", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "scientificName",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("commonName", models.CharField(max_length=100)),
                ("family", models.CharField(max_length=100)),
                ("canFlower", models.BooleanField(default=False)),
                (
                    "minTemperature",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("maxTemperature", models.FloatField()),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seeds", models.JSONField(blank=True, default=dict)),
                ("products", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "stationCode",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("station", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("solarIrradiance", models.PositiveBigIntegerField()),
                ("temperature", models.FloatField()),
                (
                    "windSpeed",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "relativeHumidity",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                (
                    "precipitation",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.user",
                    ),
                ),
                ("body", models.CharField(max_length=50)),
                ("skinTone", models.CharField(max_length=50)),
                ("eyeColor", models.CharField(max_length=50)),
                (
                    "expression",
                    models.CharField(
                        choices=[
                            ("happy", "Happy"),
                            ("sad", "Sad"),
                            ("sweating", "Sweating"),
                            ("shivering", "Shivering"),
                            ("wet", "Wet"),
                        ],
                        max_length=50,
                    ),
                ),
                ("hairColor", models.CharField(max_length=50)),
                ("hairStyle", models.CharField(max_length=50)),
                ("facialHair", models.CharField(blank=True, max_length=50)),
                ("accessories", models.JSONField(blank=True, default=list)),
                ("clothing", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="api.user",
                    ),
                ),
                ("coins", models.PositiveIntegerField(default=5)),
                ("seeds", models.JSONField(blank=True, default=dict)),
                ("products", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Garden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                ("rewardCoins", models.PositiveIntegerField()),
                ("product", models.CharField(max_length=50)),
                (
                    "seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.plant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.ImageField(
                        height_field="height",
                        upload_to=api.models.imageUploadPath,
                        width_field="width",
                    ),
                ),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                (
                    "uploader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.user",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("occupied", models.BooleanField(default=False)),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.garden"
                    ),
                ),
            ],
            options={
                "unique_together": {("garden", "number")},
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted", models.BooleanField(blank=True, null=True)),
                (
                    "requested",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to="api.user",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_requests",
                        to="api.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("requester", "requested")},
            },
        ),
        migrations.CreateModel(
            name="AlbumEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discoveryDate", models.DateField(default=django.utils.timezone.now)),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.plant"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "plant")},
            },
        ),
        migrations.CreateModel(
            name="PlantInGarden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plantedAt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "growthPhase",
                    models.CharField(
                        choices=[
                            ("seed", "Seed"),
                            ("germination", "Germination"),
                            ("growth", "Growth"),
                            ("mature", "Mature"),
                            ("flowering", "Flowering"),
                            ("dead", "Dead"),
                        ],
                        default="seed",
                        max_length=50,
                    ),
                ),
                (
                    "healthLevel",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                (
                    "waterLevel",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                (
                    "lastWateredAt",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.plant"
                    ),
                ),
                (
                    "pot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pot"
                    ),
                ),
            ],
            options={
                "unique_together": {("pot", "plant", "plantedAt")},
            },
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "missionState",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("claimed", "Claimed"),
                            ("in progress", "In Progress"),
                        ],
                        max_length=50,
                    ),
                ),
                ("acquiredAt", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.mission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "mission")},
            },
        ),
    ]
