# Generated by Django 5.2.12 on 2026-04-21 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField()),
                (
                    "effectType",
                    models.CharField(
                        choices=[
                            ("health", "Health"),
                            ("growth", "Growth"),
                            ("sun", "Sun"),
                            ("protection", "Protection"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField(blank=True, null=True)),
                ("durationHours", models.FloatField(blank=True, null=True)),
                ("price", models.PositiveIntegerField()),
                ("isInstant", models.BooleanField(default=True)),
                (
                    "image_url",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiveProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.plantingarden",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.product"
                    ),
                ),
            ],
        ),
    ]
