# Generated by Django 5.2.12 on 2026-03-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
