# Generated by Django 5.2.12 on 2026-05-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="event",
            name="street",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
