# Generated by Django 5.2.12 on 2026-05-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_event_city_alter_event_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
