# Generated by Django 5.2.12 on 2026-03-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_image_height_alter_image_width"),
        ("api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = []
