# Generated by Django 5.2.12 on 2026-03-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_image_height_alter_image_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="family",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
