# Generated by Django 5.2.12 on 2026-04-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_activeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingarden',
            name='diedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
