# Generated by Django 5.2.12 on 2026-03-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_plant_family"),
        ("api", "0003_merge_20260317_1520"),
    ]

    operations = []
