# Generated by Django 5.2.12 on 2026-03-21 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_merge_20260321_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="plantingarden",
            name="lastSimulatedAt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="user",
            name="stationCode",
            field=models.CharField(default="CC", max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="WeatherReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                ("solarIrradiance", models.FloatField(blank=True, null=True)),
                ("windSpeed", models.FloatField(blank=True, null=True)),
                ("relativeHumidity", models.FloatField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_readings",
                        to="api.station",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["station", "timestamp"],
                        name="api_weather_station_478cac_idx",
                    )
                ],
                "unique_together": {("station", "timestamp")},
            },
        ),
    ]
