# Generated by Django 5.2.12 on 2026-03-26 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_merge_20260323_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="growthPhase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seed", "Seed"),
                    ("germination", "Germination"),
                    ("growth", "Growth"),
                    ("mature", "Mature"),
                    ("flowering", "Flowering"),
                    ("dead", "Dead"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stationCode",
            field=models.CharField(default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
