# Generated by Django 5.2.12 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_merge_20260319_1331"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stationCode",
            field=models.CharField(default="W3", max_length=4),
            preserve_default=False,
        ),
    ]
