# Generated by Django 5.2.12 on 2026-03-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_plantingarden_lastsimulatedat_user_stationcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
