# Generated by Django 5.2.12 on 2026-03-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_merge_20260323_1853"),
        ("api", "0005_user_stationcode"),
        ("api", "0006_alter_plant_description"),
    ]

    operations = []
