# Generated by Django 5.2.12 on 2026-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_merge_20260325_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="growthPhase",
            field=models.CharField(
                blank=True,
                choices=[
                    ("seed", "Seed"),
                    ("germination", "Germination"),
                    ("growth", "Growth"),
                    ("mature", "Mature"),
                    ("flowering", "Flowering"),
                    ("dead", "Dead"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
