MISSIONS = [
    {
        "name": "First Plant",
        "description": "Plant your first plant.",
        "action": "PLANT",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 20,
        "productReward": None,
    },
    {
        "name": "Plant Beginner",
        "description": "Plant 3 plants.",
        "action": "PLANT",
        "goal": 3,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 50,
        "productReward": None,
    },
    {
        "name": "Plant Expert",
        "description": "Plant 10 plants.",
        "action": "PLANT",
        "goal": 10,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 120,
        "productReward": "Small Heal",
    },
    {
        "name": "Water Beginner",
        "description": "Water plants 3 times.",
        "action": "WATER",
        "goal": 3,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 30,
        "productReward": None,
    },
    {
        "name": "Water Routine",
        "description": "Water plants 10 times.",
        "action": "WATER",
        "goal": 10,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 80,
        "productReward": "Hydration Shield",
    },
    {
        "name": "Water Master",
        "description": "Water plants 25 times.",
        "action": "WATER",
        "goal": 25,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 150,
        "productReward": None,
    },
    {
        "name": "First Collection",
        "description": "Collect your first plant.",
        "action": "COLLECT",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 40,
        "productReward": None,
    },
    {
        "name": "Plant Collector",
        "description": "Collect 5 plants.",
        "action": "COLLECT",
        "goal": 5,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 120,
        "productReward": "Medium Heal",
    },
    {
        "name": "Collection Master",
        "description": "Collect 15 plants.",
        "action": "COLLECT",
        "goal": 15,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 250,
        "productReward": None,
    },
    {
        "name": "First Flower",
        "description": "Make one plant reach the flowering stage.",
        "action": "FLOWER",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 80,
        "productReward": None,
    },
    {
        "name": "Flower Garden",
        "description": "Make 3 plants reach the flowering stage.",
        "action": "FLOWER",
        "goal": 3,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 180,
        "productReward": "Phase Boost",
    },
    {
        "name": "Use First Product",
        "description": "Use one product.",
        "action": "USE",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 25,
        "productReward": None,
    },
    {
        "name": "Use Small Heal",
        "description": "Use a Small Heal product once.",
        "action": "USE",
        "goal": 1,
        "plant": None,
        "product": "Small Heal",
        "plantReward": None,
        "rewardCoins": 35,
        "productReward": None,
    },
    {
        "name": "Use Phase Boost",
        "description": "Use a Phase Boost product once.",
        "action": "USE",
        "goal": 1,
        "plant": None,
        "product": "Phase Boost",
        "plantReward": None,
        "rewardCoins": 70,
        "productReward": None,
    },
    {
        "name": "Plant Photographer",
        "description": "Take one photo of a plant.",
        "action": "PHOTO",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 30,
        "productReward": None,
    },
    {
        "name": "Photo Lover",
        "description": "Take 5 photos of your plants.",
        "action": "PHOTO",
        "goal": 5,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 90,
        "productReward": None,
    },
    {
        "name": "Hard Lesson",
        "description": "Have one plant die.",
        "action": "DIE",
        "goal": 1,
        "plant": None,
        "product": None,
        "plantReward": None,
        "rewardCoins": 20,
        "productReward": "Revive",
    },
]