STARTER_PLANTS = [
    {
        "scientificName": "helianthus_annuus",
        "commonName": "Sunflower",
        "family": "Asteraceae",
        "canFlower": True,
        "minTemperature": 10.0,
        "maxTemperature": 35.0,
        "description": "A tall annual plant known for its large yellow flower head.",
    },
    {
        "scientificName": "dianthus_caryophyllus",
        "commonName": "Carnation",
        "family": "Caryophyllaceae",
        "canFlower": True,
        "minTemperature": 7.0,
        "maxTemperature": 30.0,
        "description": "A fragrant flowering plant with ruffled petals.",
    },
    {
        "scientificName": "rosa_canina",
        "commonName": "Dog Rose",
        "family": "Rosaceae",
        "canFlower": True,
        "minTemperature": 5.0,
        "maxTemperature": 30.0,
        "description": "A wild rose species with pink flowers and red hips.",
    },
    {
        "scientificName": "lavandula_angustifolia",
        "commonName": "Lavender",
        "family": "Lamiaceae",
        "canFlower": True,
        "minTemperature": 5.0,
        "maxTemperature": 35.0,
        "description": "An aromatic shrub with purple flower spikes.",
    },
    {
        "scientificName": "mentha_spicata",
        "commonName": "Spearmint",
        "family": "Lamiaceae",
        "canFlower": True,
        "minTemperature": 5.0,
        "maxTemperature": 30.0,
        "description": "A fragrant herb widely used in cooking and medicine.",
    },
]