STARTER_PLANTS = [
    {
        "scientificName": "dahlia_pinnata",
        "commonName": "dahlia",
        "family": "asteraceae",
        "canFlower": True,
        "minTemperature": 8,
        "maxTemperature": 30,
        "description": "Dahlias are flowering plants known for their colorful blooms and ornamental value.",
    },
    {
        "scientificName": "rosa_rugosa",
        "commonName": "rosa rugosa",
        "family": "rosaceae",
        "canFlower": True,
        "minTemperature": 5,
        "maxTemperature": 30,
        "description": "Rosa rugosa is a hardy flowering shrub known for its fragrant flowers and resistance to harsh conditions.",
    },
    {
        "scientificName": "orchidaceae",
        "commonName": "orquidea",
        "family": "orquideas",
        "canFlower": True,
        "minTemperature": 2,
        "maxTemperature": 30,
        "description": "Orchids are plants that belong to the Orchidaceae family and are known for their ornamental flowers.",
    },
    {
        "scientificName": "dendrobium_anosmum",
        "commonName": "dendrobium anosmum",
        "family": "orchidaceae",
        "canFlower": True,
        "minTemperature": 14,
        "maxTemperature": 30,
        "description": "Dendrobium anosmum is a species of orchid known for its hanging stems and fragrant flowers.",
    },
]
