PRODUCTS = [
    {
        "name": "Full Heal",
        "description": "Fully restores plant health.",
        "effectType": "health",
        "value": 100.0,
        "durationHours": None,
        "price": 50,
        "isInstant": True,
        "image_url": "products/pocio_salut_max.png",
        "rarity": "rare",
    },
    {
        "name": "Hydration Shield",
        "description": "Reduces water loss.",
        "effectType": "water_protection",
        "value": 100.0,
        "durationHours": None,
        "price": 30,
        "isInstant": True,
        "image_url": "products/pocio_aigua_transparent.png",
        "rarity": "common",
    },
    {
        "name": "Medium Heal",
        "description": "Restores a moderate amount of plant health.",
        "effectType": "health",
        "value": 50.0,
        "durationHours": None,
        "price": 25,
        "isInstant": True,
        "image_url": "products/pocio_salut_transparent.png",
        "rarity": "common",
    },
    {
        "name": "Phase Boost",
        "description": "Advances the plant growth stage 24 hours.",
        "effectType": "growth",
        "value": 24.0,
        "durationHours": None,
        "price": 80,
        "isInstant": True,
        "image_url": "products/pocio_creixement_transparent.png",
        "rarity": "rare",
    },
    {
        "name": "Protection Shield",
        "description": "Prevents health loss from weather conditions.",
        "effectType": "meteo_protection",
        "value": 1.0,
        "durationHours": 12.0,
        "price": 60,
        "isInstant": False,
        "image_url": "products/pocio_meteo.png",
        "rarity": "rare",
    },
    {
        "name": "Revive",
        "description": "Revives a dead plant with partial health.",
        "effectType": "revive",
        "value": 20.0,
        "durationHours": None,
        "price": 90,
        "isInstant": True,
        "image_url": "products/pocio_reviure.jpng",
        "rarity": "epic",
    },
    {
        "name": "Small Heal",
        "description": "Restores a small amount of plant health.",
        "effectType": "health",
        "value": 20.0,
        "durationHours": None,
        "price": 10,
        "isInstant": True,
        "image_url": "products/pocio_salut_mini.png",
        "rarity": "common",
    },
    {
        "name": "Solar Shield",
        "description": "Protects against intense sunlight and dry air.",
        "effectType": "sun_protection",
        "value": None,
        "durationHours": 12.0,
        "price": 20,
        "isInstant": False,
        "image_url": "products/solar_shield.png",
        "rarity": "common",
    },
    {
        "name": "Temperature Shield",
        "description": "Stabilizes the plant against extreme temperatures.",
        "effectType": "temp_protection",
        "value": None,
        "durationHours": 12.0,
        "price": 20,
        "isInstant": False,
        "image_url": "products/temp_shield.png",
        "rarity": "rare",
    },
    {
        "name": "Wind Shield",
        "description": "Prevents damage caused by strong winds.",
        "effectType": "wind_protection",
        "value": None,
        "durationHours": 12.0,
        "price": 20,
        "isInstant": False,
        "image_url": "products/wind_shield_transparent.png",
        "rarity": "common",
    },
]
