PRODUCTS = [
    {
        "name": "Small Heal",
        "description": "Restores a small amount of plant health.",
        "effectType": "health",
        "value": 20,
        "isInstant": True,
        "price": 10,
        "rarity": "common",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_salut_mini.png",
    },
    {
        "name": "Medium Heal",
        "description": "Restores a moderate amount of plant health.",
        "effectType": "health",
        "value": 50,
        "isInstant": True,
        "price": 25,
        "rarity": "common",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_salut.png",
    },
    {
        "name": "Full Heal",
        "description": "Fully restores plant health.",
        "effectType": "health",
        "value": 100,
        "isInstant": True,
        "price": 50,
        "rarity": "rare",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_salut_max.jpeg",
    },
    {
        "name": "Phase Boost",
        "description": "Advances the plant growth stage 24 hours.",
        "effectType": "growth",
        "value": 24,
        "isInstant": True,
        "price": 80,
        "rarity": "rare",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_creixement.png",
    },
    {
        "name": "Revive",
        "description": "Revives a dead plant with partial health.",
        "effectType": "revive",
        "value": 20,
        "isInstant": True,
        "price": 90,
        "rarity": "epic",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_reviure.jpeg",
    },
    {
        "name": "Hydration Shield",
        "description": "Reduces water loss over time.",
        "effectType": "water_protection",
        "value": 1,
        "durationHours": 24,
        "isInstant": False,
        "price": 30,
        "rarity": "common",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_aigua.png",
    },
    {
        "name": "Protection Shield",
        "description": "Prevents health loss from weather conditions.",
        "effectType": "meteo_protection",
        "value": 1,
        "durationHours": 12,
        "isInstant": False,
        "price": 60,
        "rarity": "rare",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/pocio_meteo.jpeg",
    },
    {
        "name": "Solar Shield",
        "description": "Protects against intense sunlight and dry air.",
        "effectType": "sun_protection",
        "durationHours": 12,
        "isInstant": False,
        "price": 20,
        "rarity": "common",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/solar_shield.png",
    },
    {
        "name": "Wind Shield",
        "description": "Prevents damage caused by strong winds.",
        "effectType": "wind_protection",
        "durationHours": 12,
        "isInstant": False,
        "price": 20,
        "rarity": "common",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/wind_shield.png",
    },
    {
        "name": "Temperature Shield",
        "description": "Stabilizes the plant against extreme temperatures.",
        "effectType": "temp_protection",
        "durationHours": 12,
        "isInstant": False,
        "price": 20,
        "rarity": "rare",
        "image_url": "https://meteogarden-images.s3.eu-south-2.amazonaws.com/products/temp_shield.png",
    },
]
