"""
URL configuration for api.
"""

# from django.contrib import admin
from django.urls import path

from .views import (
    answer_request,
    assign_mission,
    avatar,
    buy_item,
    cancel_request,
    claim_reward,
    collect_plant,
    create_mission,
    current_weather,
    delete_fcm_token,
    delete_friend,
    delete_plant,
    delete_profile,
    edit_profile,
    garden_plants,
    get_categories,
    get_event_detail,
    get_events,
    get_missions,
    get_num_events,
    get_profile,
    get_requests,
    get_shop,
    get_shop_product,
    get_shop_seed,
    get_stations,
    get_user_missions,
    get_users_friends,
    getUserAlbum,
    getUserAvatar,
    google_register,
    google_verify,
    health,
    identifyPlant,
    importPlant,
    like_friend,
    login,
    plant_seed,
    plant_status,
    register,
    save_fcm_token,
    saveAvatar,
    search_users,
    send_friend_request,
    translate,
    use_product,
    user_gardens,
    user_products,
    user_seeds,
    validate_token,
    water_plant,
)

urlpatterns = [
    path("health/", health),
    path("register/", register, name="register"),
    path("login/", login, name="login"),
    path("get_profile/", get_profile, name="get_profile"),
    path("edit_profile/", edit_profile, name="edit_profile"),
    path("delete_profile/", delete_profile, name="delete_profile"),
    path("auth/google/verify", google_verify, name="google_verify"),
    path("auth/google/register", google_register, name="google_register"),
    path("validate_token/", validate_token, name="validate_token"),
    path("users/<str:username>/gardens/", user_gardens, name="user_gardens"),
    path(
        "users/<str:username>/gardens/<str:garden_name>/plants/",
        garden_plants,
        name="garden-plants",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/plant/",
        plant_status,
        name="plant_status",
    ),
    path("weather/current/", current_weather, name="current_weather"),
    path("stations/", get_stations, name="get_stations"),
    path("plants/info/", importPlant, name="importPlant"),
    path("plants/identify", identifyPlant, name="identifyPlant"),
    path("users/<str:username>/album/", getUserAlbum),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/water/",
        water_plant,
        name="water_plant",
    ),
    path(
        "users/<str:username>/seeds/",
        user_seeds,
        name="user_seeds",
    ),
    path(
        "users/<str:username>/products/",
        user_products,
        name="user_products",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/planting/",
        plant_seed,
        name="plant_seed",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/collect/",
        collect_plant,
        name="collect_plant",
    ),
    path("translate/", translate),
    path("shop/", get_shop, name="get_shop"),
    path("shop/products/<str:name>", get_shop_product, name="get_shop_product"),
    path("shop/seeds/<str:scientific_name>", get_shop_seed, name="get_shop_seed"),
    path("save-token/", save_fcm_token),
    path("delete-token/", delete_fcm_token),
    path("users/<str:username>/buy/", buy_item, name="buy_item"),
    path("use_product/", use_product),
    path("avatar/", avatar, name="avatar_images"),
    path("users/<str:username>/avatar/", getUserAvatar, name="user_avatar"),
    path("users/<str:username>/save/avatar/", saveAvatar, name="save_avatar"),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/delete/",
        delete_plant,
        name="delete_plant",
    ),
    path("events/", get_events, name="events"),
    path("events/count", get_num_events, name="num_events"),
    path("events/detail", get_event_detail, name="event_detail"),
    path("events/categories", get_categories, name="categories_info"),
    path("user/missions/", get_user_missions, name="getUserMissions"),
    path("missions/create/", create_mission, name="createMission"),
    path("missions/", get_missions, name="getMissions"),
    path("missions/assign/", assign_mission, name="assignMission"),
    path("user/missions/claim/", claim_reward, name="claimReward"),
    path("friends/send_request/", send_friend_request, name="sendFriendRequest"),
    path("friends/cancel_request/", cancel_request, name="cancelRequest"),
    path("friends/answer_request/", answer_request, name="answerRequest"),
    path("friends/requests/", get_requests, name="get_requests"),
    path("friends/", get_users_friends, name="get_users_friends"),
    path("search/", search_users, name="search_users"),
    path("friends/<str:username>", delete_friend, name="delete_friend"),
    path("friends/likes/<str:username>/", like_friend, name="like_friend"),
]
