"""
URL configuration for api.
"""

# from django.contrib import admin
from django.urls import path

from .views import (
    answerRequest,
    assignMission,
    avatar,
    buy_item,
    cancelRequest,
    claimReward,
    collect_plant,
    createMission,
    current_weather,
    delete_plant,
    delete_profile,
    edit_profile,
    garden_plants,
    get_profile,
    get_shop,
    get_stations,
    getEventDetail,
    getEvents,
    getEventsByCategory,
    getEventsByCity,
    getMissions,
    getNumEvents,
    getRequests,
    getUserAlbum,
    getUserAvatar,
    getUserMissions,
    google_register,
    google_verify,
    health,
    identifyPlant,
    importPlant,
    login,
    plant_seed,
    plant_status,
    register,
    save_fcm_token,
    saveAvatar,
    sendFriendRequest,
    translate,
    use_product,
    user_gardens,
    user_products,
    user_seeds,
    validate_token,
    water_plant,
)

urlpatterns = [
    path("health/", health),
    path("register/", register),
    path("login/", login),
    path("get_profile/", get_profile),
    path("edit_profile/", edit_profile),
    path("delete_profile/", delete_profile),
    path("auth/google/verify", google_verify),
    path("auth/google/register", google_register),
    path("validate_token/", validate_token),
    path("users/<str:username>/gardens/", user_gardens, name="user_gardens"),
    path(
        "users/<str:username>/gardens/<str:garden_name>/plants/",
        garden_plants,
        name="garden-plants",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/plant/",
        plant_status,
        name="plant_status",
    ),
    path("weather/current/", current_weather),
    path("stations/", get_stations),
    path("plants/info/", importPlant),
    path("plants/identify", identifyPlant, name="identifyPlant"),
    path("users/<str:username>/album/", getUserAlbum),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/water/",
        water_plant,
        name="water_plant",
    ),
    path(
        "users/<str:username>/seeds/",
        user_seeds,
        name="user_seeds",
    ),
    path(
        "users/<str:username>/products/",
        user_products,
        name="user_products",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/planting/",
        plant_seed,
        name="plant_seed",
    ),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/collect/",
        collect_plant,
        name="collect_plant",
    ),
    path("translate/", translate),
    path("shop/", get_shop, name="get_shop"),
    path("save-token/", save_fcm_token),
    path("users/<str:username>/buy/", buy_item, name="buy_item"),
    path("use_product/", use_product),
    path("avatar/", avatar, name="avatar_images"),
    path("users/<str:username>/avatar", getUserAvatar, name="user_avatar"),
    path("users/<str:username>/save/avatar", saveAvatar, name="save_avatar"),
    path(
        "users/<str:username>/gardens/<str:garden_name>/pots/<int:pot_number>/delete/",
        delete_plant,
        name="delete_plant",
    ),
    path("events/", getEvents, name="events"),
    path("events/count", getNumEvents, name="num_events"),
    path("events/detail", getEventDetail, name="event_detail"),
    path("events/city", getEventsByCity, name="events_by_city"),
    path("events/category", getEventsByCategory, name="events_by_category"),
    path("user/missions/", getUserMissions, name="getUserMissions"),
    path("missions/create/", createMission, name="createMission"),
    path("missions/", getMissions, name="getMissions"),
    path("missions/assign/", assignMission, name="assignMission"),
    path("user/missions/claim/", claimReward, name="claimReward"),
    path("friends/send_request/", sendFriendRequest, name="sendFriendRequest"),
    path("friends/cancel_request/", cancelRequest, name="cancelRequest"),
    path("friends/answer_request/", answerRequest, name="answerRequest"),
    path("friends/requests/", getRequests, name="getRequests"),
]
