# Generated by Django 5.2.12 on 2026-05-01 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "stationCode",
                    models.CharField(max_length=4, primary_key=True, serialize=False),
                ),
                ("station", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("solarIrradiance", models.PositiveBigIntegerField()),
                ("temperature", models.FloatField()),
                (
                    "precipitation",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("updateDate", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("precipitation", models.FloatField(blank=True, null=True)),
                ("solarIrradiance", models.FloatField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_readings",
                        to="third_party_service.station",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["station", "timestamp"],
                        name="third_party_station_f0dd30_idx",
                    )
                ],
                "unique_together": {("station", "timestamp")},
            },
        ),
    ]
